Create input component
athostravel/athos pull request #42
Opened 2019-12-19 16:07 UTC by xiscovich

Add input component

2019-12-19 16:10 UTC, JorgeRaboso commented on docs/.vuepress/config.js
> +                                '/es/documentacion/components/input'
Ordenar alfabeticamente

2019-12-19 16:11 UTC, JorgeRaboso commented on docs/es/documentacion/components/input.md
> +<Preview>
La documentación no esta bien implementada, comentar con Javi

2019-12-19 16:12 UTC, ghost requested changes

2019-12-19 16:12 UTC, JorgeRaboso commented on src/components/index.js
> +export { default as Input } from '@components/Input'
Ordenar

2019-12-20 11:02 UTC, xiscovich commented on docs/.vuepress/config.js
> +                                '/es/documentacion/components/input'
Hecho

2019-12-20 11:02 UTC, xiscovich commented on src/components/index.js
> +export { default as Input } from '@components/Input'
Hecho

2019-12-20 11:11 UTC, xiscovich commented on docs/es/documentacion/components/input.md
> +<Preview>
Hecho

2019-12-20 11:19 UTC, ghost approved these changes

2020-01-21 09:14 UTC, merged